# Generated by Django 2.1.7 on 2019-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0006_auto_20190401_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontext',
            name='current_metrics_of_interest',
            field=models.TextField(null=True),
        ),
    ]
