# Generated by Django 2.1.7 on 2019-05-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0007_edlcontext_current_metrics_of_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDLContextScorecards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_scorecard_df_fail_arr',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_fail_scorecards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_API.EDLContext'),
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='user_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_API.UserInformation'),
        ),
    ]
