version: '3.7'
services:
  brain:
    build:
      dockerfile: Dockerfile
      context: .
    image: 923405430231.dkr.ecr.us-east-2.amazonaws.com/brain
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    container_name: brain
    command: bash
networks:
  default:
    name: daphne-network
    external: true
