version: '3.7'
services:
  brain:
    build:
      dockerfile: Dockerfile
      context: .
    image: 923405430231.dkr.ecr.us-east-2.amazonaws.com/brain
    environment:
      # --> Config
      - DAPHNEVERSION=${DAPHNEVERSION}
      - VASSAR_HOST=${VASSAR_HOST}
      - VASSAR_PORT=${VASSAR_PORT}
      - DATAMINING_HOST=${DATAMINING_HOST}
      - DATAMINING_PORT=${DATAMINING_PORT}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - VASSAR_REQUEST_URL=${VASSAR_REQUEST_URL}
      - VASSAR_RESPONSE_URL=${VASSAR_RESPONSE_URL}
      - GA_REQUEST_URL=${GA_REQUEST_URL}
      - GA_RESPONSE_URL=${GA_RESPONSE_URL}
      - DEPLOYMENT_TYPE=${DEPLOYMENT_TYPE}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

      # --> DBs
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

      # --> Services
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_PORT=${NEO4J_PORT}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - HASURA_HOST=${HASURA_HOST}
      - HASURA_HOST_WS=${HASURA_HOST_WS}
      - CLUSTER_ARN=${CLUSTER_ARN}
      - VASSAR_SERVICE_ARN=${VASSAR_SERVICE_ARN}
      - GA_SERVICE_ARN=${GA_SERVICE_ARN}
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    container_name: brain
    command: bash
networks:
  default:
    name: daphne-network
    external: true
