# Generated by Django 2.1.12 on 2019-09-22 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('engineer', 'Engineer Commands'), ('critic', 'Critic Commands'), ('historian', 'Historian Commands'), ('analyst', 'iFEED Commands'), ('analyst_instruments', 'Instruments Cheatsheet'), ('analyst_instrument_parameters', 'Instrument Parameters Cheatsheet'), ('analyst_measurements', 'Measurements Cheatsheet'), ('analyst_stakeholders', 'Stakeholders Cheatsheet'), ('measurements', 'Historical Measurements Cheatsheet'), ('missions', 'Historical Missions Cheatsheet'), ('technologies', 'Historical Technologies Cheatsheet'), ('objectives', 'Objectives Cheatsheet'), ('space_agencies', 'Space Agencies Cheatsheet')], max_length=40)),
                ('command_descriptor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_answer', models.TextField()),
                ('visual_answer_type', models.TextField()),
                ('visual_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField()),
                ('experiment_id', models.IntegerField()),
                ('current_state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('end_state', models.TextField()),
                ('experimentcontext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.ExperimentContext')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daphne_version', models.CharField(choices=[('EOSS', 'Earth Observation Satellite Systems'), ('EDL', 'Entry, Descent & Landing'), ('AT', 'Anomaly Detection for Astronauts')], max_length=40)),
                ('channel_name', models.CharField(max_length=120)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experimentcontext',
            name='user_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation'),
        ),
        migrations.AddField(
            model_name='experimentaction',
            name='experimentstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.ExperimentStage'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation'),
        ),
        migrations.AddField(
            model_name='allowedcommand',
            name='user_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation'),
        ),
        migrations.AlterUniqueTogether(
            name='userinformation',
            unique_together={('session', 'user')},
        ),
    ]
