# Generated by Django 2.1.12 on 2019-09-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_message', models.TextField()),
                ('visual_message_type', models.TextField()),
                ('visual_message', models.TextField()),
                ('writer', models.CharField(choices=[('user', 'Human'), ('daphne', 'Machine')], max_length=40)),
                ('date', models.DateTimeField()),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_information',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
