# Generated by Django 2.1.12 on 2019-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0003_dialoguecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguecontext',
            name='clarifying_commands',
            field=models.TextField(null=True),
        ),
    ]
