# Generated by Django 2.1.12 on 2019-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0005_dialoguecontext_clarifying_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoguecontext',
            name='clarifying_role',
            field=models.IntegerField(null=True),
        ),
    ]
