# Generated by Django 2.2.8 on 2019-12-08 02:06

import mycroft.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0007_auto_20191111_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mycroft_session',
            field=models.CharField(default=mycroft.utils.generate_mycroft_session, max_length=9),
        ),
    ]
