# Generated by Django 2.2.8 on 2019-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0008_userinformation_mycroft_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mycroft_channel_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
