# Generated by Django 2.2.9 on 2020-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0009_userinformation_mycroft_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mycroft_connection',
            field=models.BooleanField(default=False),
        ),
    ]
