# Generated by Django 2.2.11 on 2020-11-09 17:00

import daphne_context.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daphne_context', '0010_userinformation_mycroft_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='mycroft_session',
        ),
        migrations.CreateModel(
            name='MycroftUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycroft_session', models.CharField(default=daphne_context.utils.generate_mycroft_session, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
