# Generated by Django 3.1.7 on 2021-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0012_auto_20210322_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='formulation_agent',
            field=models.BinaryField(null=True),
        ),
    ]
