# Generated by Django 3.2.10 on 2022-01-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0013_userinformation_is_experiment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mycroft_session',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='MycroftUser',
        ),
    ]
