# Generated by Django 3.1.7 on 2021-10-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0013_userinformation_formulation_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='formulation_agent',
        ),
    ]
