# Generated by Django 3.1.7 on 2021-11-12 15:49

import daphne_context.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0014_remove_userinformation_formulation_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycroftuser',
            name='mycroft_session',
            field=models.CharField(default=daphne_context.utils.generate_mycroft_session, max_length=9, null=True),
        ),
    ]
