# Generated by Django 4.0.3 on 2022-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0014_auto_20211231_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='is_domain_expert',
            field=models.BooleanField(default=False),
        ),
    ]
