# Generated by Django 3.1.7 on 2021-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0015_auto_20211112_0949'),
        ('daphne_context', '0015_auto_20211123_1336'),
    ]

    operations = [
    ]
