# Generated by Django 3.1.7 on 2021-11-30 01:06

import daphne_context.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0016_merge_20211129_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='eval_request_queue',
            field=models.TextField(default=daphne_context.models.get_eval_request_queue, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='eval_response_queue',
            field=models.TextField(default=daphne_context.models.get_eval_response_queue, null=True),
        ),
    ]
