# Generated by Django 3.1.7 on 2021-12-01 02:36

import daphne_context.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0018_auto_20211130_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='eval_request_queue',
            field=models.TextField(default=daphne_context.models.get_eval_request_queue, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='eval_response_queue',
            field=models.TextField(default=daphne_context.models.get_eval_response_queue, null=True),
        ),
    ]
