# Generated by Django 3.1.7 on 2021-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0019_auto_20211130_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='eval_request_queue',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='eval_response_queue',
            field=models.TextField(null=True),
        ),
    ]
