# Generated by Django 2.1.12 on 2019-09-22 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daphne_context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDLContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mat_file', models.CharField(max_length=255)),
                ('current_mat_file_for_print', models.CharField(max_length=255)),
                ('current_scorecard_file', models.CharField(max_length=255)),
                ('current_scorecard', models.CharField(max_length=255)),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
    ]
