# Generated by Django 2.1.12 on 2019-10-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDLContextScorecards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorecard_name', models.CharField(default='', max_length=225)),
                ('current_scorecard_path', models.CharField(default='', max_length=255)),
                ('current_scorecard_df', models.BinaryField(default=b'')),
                ('current_scorecard_df_flag', models.BinaryField(default=b'')),
                ('current_scorecard_df_fail', models.BinaryField(default=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='edlcontext',
            name='current_scorecard',
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_metrics_of_interest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_mission',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_scorecard_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='selected_case',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='edl_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDL.EDLContext'),
        ),
    ]
