# Generated by Django 2.1.12 on 2019-10-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDL', '0003_edlcontextscorecards_current_corr_mat_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_corr_mat_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
