# Generated by Django 2.1.12 on 2019-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDL', '0004_edlcontextscorecards_current_corr_mat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edlcontextscorecards',
            name='current_corr_mat_status',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
