# Generated by Django 2.1.12 on 2019-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDL', '0005_auto_20191021_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontext',
            name='current_cormat_df',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_cormat_status',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
