# Generated by Django 2.1.12 on 2020-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDL', '0006_auto_20191021_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_scorecard_df_db',
            field=models.BinaryField(default=b''),
        ),
    ]
