# Generated by Django 2.1.3 on 2018-11-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_background_search_feedback', models.BooleanField()),
                ('check_for_diversity', models.BooleanField()),
                ('show_arch_suggestions', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineerContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vassar_instrument', models.TextField()),
                ('instrument_parameter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EOSSContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=80)),
                ('last_arch_id', models.IntegerField()),
                ('selected_arch_id', models.IntegerField()),
                ('vassar_port', models.IntegerField()),
                ('active_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_API.ActiveContext')),
                ('engineer_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_API.EngineerContext')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, null=True, verbose_name='session key')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='username')),
                ('daphne_version', models.CharField(choices=[('EOSS', 'Earth Observation Satellite Systems'), ('EDL', 'Entry, Descent & Landing'), ('AnomalyDetection', 'Anomaly Detection for Astronauts')], max_length=40)),
                ('eoss_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_API.EOSSContext')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userinformation',
            unique_together={('session_key', 'username')},
        ),
    ]
