# Generated by Django 2.1.3 on 2018-11-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='added_archs_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
