# Generated by Django 2.1.3 on 2018-11-08 22:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('daphne_API', '0002_auto_20181108_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='session_key',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userinformation',
            unique_together={('session', 'user')},
        ),
    ]
