# Generated by Django 2.1.3 on 2018-11-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0003_auto_20181108_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merge_session.MergeSession'),
        ),
    ]
