# Generated by Django 2.1.3 on 2018-11-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0004_auto_20181108_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosscontext',
            name='active_context',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='engineer_context',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='eoss_context',
        ),
        migrations.AddField(
            model_name='activecontext',
            name='eosscontext',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='daphne_API.EOSSContext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineercontext',
            name='eosscontext',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='daphne_API.EOSSContext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='user_information',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='daphne_API.UserInformation'),
            preserve_default=False,
        ),
    ]
