# Generated by Django 2.1.7 on 2019-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0004_edlcontext_selected_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontext',
            name='current_mission',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
