# Generated by Django 2.1.7 on 2019-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0005_edlcontext_current_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontext',
            name='current_scorecard_df',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_scorecard_df_fail',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edlcontext',
            name='current_scorecard_df_flag',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
