# Generated by Django 2.1.7 on 2019-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0008_auto_20190507_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edlcontextscorecards',
            old_name='current_fail_scorecards',
            new_name='edl_context',
        ),
        migrations.RemoveField(
            model_name='edlcontext',
            name='current_scorecard_df',
        ),
        migrations.RemoveField(
            model_name='edlcontext',
            name='current_scorecard_df_fail',
        ),
        migrations.RemoveField(
            model_name='edlcontext',
            name='current_scorecard_df_fail_arr',
        ),
        migrations.RemoveField(
            model_name='edlcontext',
            name='current_scorecard_df_flag',
        ),
        migrations.RemoveField(
            model_name='edlcontextscorecards',
            name='user_information',
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_scorecard_df',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_scorecard_df_fail',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_scorecard_df_flag',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='scorecard_name',
            field=models.CharField(default='', max_length=225),
        ),
    ]
