# Generated by Django 2.1.7 on 2019-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_API', '0009_auto_20190507_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlcontextscorecards',
            name='current_scorecard_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
