# Generated by Django 2.1.12 on 2019-09-22 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daphne_context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_background_search_feedback', models.BooleanField(default=False)),
                ('check_for_diversity', models.BooleanField(default=True)),
                ('show_arch_suggestions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('inputs', models.TextField()),
                ('outputs', models.TextField()),
                ('activecontext', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EOSS.ActiveContext')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vassar_instrument', models.TextField()),
                ('instrument_parameter', models.TextField()),
                ('vassar_measurement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EOSSContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=80)),
                ('dataset_user', models.BooleanField()),
                ('last_arch_id', models.IntegerField()),
                ('selected_arch_id', models.IntegerField()),
                ('added_archs_count', models.IntegerField()),
                ('vassar_port', models.IntegerField()),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
        migrations.AddField(
            model_name='engineercontext',
            name='eosscontext',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EOSS.EOSSContext'),
        ),
        migrations.AddField(
            model_name='design',
            name='eosscontext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EOSS.EOSSContext'),
        ),
        migrations.AddField(
            model_name='activecontext',
            name='eosscontext',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EOSS.EOSSContext'),
        ),
        migrations.AlterUniqueTogether(
            name='design',
            unique_together={('eosscontext', 'activecontext', 'id')},
        ),
    ]
