# Generated by Django 2.1.12 on 2019-10-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0003_dialoguecontext'),
        ('EOSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOSSDialogueContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialoguecontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.DialogueContext')),
            ],
        ),
        migrations.RemoveField(
            model_name='engineercontext',
            name='eosscontext',
        ),
        migrations.AddField(
            model_name='engineercontext',
            name='eossdialoguecontext',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='EOSS.EOSSDialogueContext'),
            preserve_default=False,
        ),
    ]
