# Generated by Django 2.1.13 on 2019-10-30 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0001_initial'),
        ('EOSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturesClicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_clicked', models.TextField(max_length=500)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturesEvaluated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_evaluated', models.TextField(max_length=500)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturesUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_updated', models.TextField(max_length=500)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
    ]
