# Generated by Django 2.2.8 on 2019-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0004_eosscontext_ga_id'),
        ('EOSS', '0002_architecturesclicked_architecturesevaluated_architecturesupdated'),
    ]

    operations = [
    ]
