# Generated by Django 2.2.10 on 2020-02-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0004_eosscontext_ga_id'),
        ('EOSS', '0002_architecturesclicked_architecturesevaluated_architecturesupdated'),
    ]

    operations = [
    ]
