# Generated by Django 2.2.11 on 2020-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0005_eosscontext_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosscontext',
            name='problem_id',
            field=models.IntegerField(default=4),
        ),
    ]
