# Generated by Django 3.1.7 on 2021-03-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0007_eosscontext_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosscontext',
            name='dataset_name',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='dataset_user',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='vassar_port',
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='dataset_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eosscontext',
            name='problem_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
