# Generated by Django 3.1.7 on 2021-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0009_auto_20210401_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='vassar_ready',
            field=models.BooleanField(default=False),
        ),
    ]
