# Generated by Django 3.1.7 on 2021-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0010_eosscontext_vassar_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eosscontext',
            old_name='vassar_queue_url',
            new_name='vassar_request_queue_url',
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='vassar_response_queue_url',
            field=models.TextField(null=True),
        ),
    ]
