# Generated by Django 3.1.7 on 2021-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0011_auto_20210413_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosscontext',
            name='vassar_ready',
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='ga_information',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='ga_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='ga_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='vassar_information',
            field=models.JSONField(default=dict),
        ),
    ]
