# Generated by Django 3.1.7 on 2021-11-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0012_auto_20210422_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='ga_thread_id',
            field=models.IntegerField(default=-1),
        ),
    ]
