# Generated by Django 4.0.3 on 2022-03-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0005_merge_20191208_1054'),
        ('EOSS', '0005_merge_20200225_1330'),
        ('EOSS', '0013_eosscontext_ga_thread_id'),
    ]

    operations = [
    ]
