# Generated by Django 4.0.3 on 2022-04-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0015_remove_activecontext_show_arch_suggestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineercontext',
            name='measurement_parameter',
            field=models.TextField(null=True),
        ),
    ]
