# Generated by Django 4.1.1 on 2022-09-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0016_engineercontext_measurement_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='cluster_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='cluster_name',
            field=models.TextField(default='daphne-cluster'),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_request_queue_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_request_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_response_queue_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_response_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_service_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_service_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_task_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_task_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='eval_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='eval_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_service_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_service_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_task_arn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_task_name',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='EvaluatorInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_request_queue_url', models.TextField(null=True)),
                ('ping_response_queue_url', models.TextField(null=True)),
                ('private_request_queue_url', models.TextField(null=True)),
                ('private_response_queue_url', models.TextField(null=True)),
                ('arn', models.TextField(null=True)),
                ('eosscontext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOSS.eosscontext')),
            ],
        ),
    ]
