# Generated by Django 4.1.1 on 2022-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0018_alter_eosscontext_cluster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosscontext',
            name='cluster_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_request_queue_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_response_queue_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_service_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_service_name',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_task_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='design_evaluator_task_name',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='genetic_algorithm_service_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='genetic_algorithm_service_name',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='genetic_algorithm_task_arn',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='genetic_algorithm_task_count',
        ),
        migrations.RemoveField(
            model_name='eosscontext',
            name='genetic_algorithm_task_name',
        ),
        migrations.AlterField(
            model_name='activecontext',
            name='check_for_diversity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activecontext',
            name='show_analyst_suggestions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activecontext',
            name='show_engineer_suggestions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activecontext',
            name='show_historian_suggestions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eosscontext',
            name='design_evaluator_task_count',
            field=models.IntegerField(default=1),
        ),
    ]
