# Generated by Django 4.1.1 on 2022-09-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0019_remove_eosscontext_cluster_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_request_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_response_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_task_count',
            field=models.IntegerField(default=1),
        ),
    ]
