# Generated by Django 4.1.1 on 2022-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0020_eosscontext_genetic_algorithm_request_queue_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosscontext',
            name='design_evaluator_service_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eosscontext',
            name='genetic_algorithm_service_lock',
            field=models.BooleanField(default=False),
        ),
    ]
