# Generated by Django 4.1.1 on 2022-10-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOSS', '0026_alter_eosscontext_design_evaluator_instance_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosscontext',
            name='design_evaluator_instance_count',
            field=models.IntegerField(default=3),
        ),
    ]
