# Generated by Django 2.2.8 on 2020-02-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daphne_context', '0007_auto_20191111_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_anomaly', models.CharField(max_length=80)),
                ('current_step', models.IntegerField()),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.UserInformation')),
            ],
        ),
    ]
