# Generated by Django 2.2.8 on 2020-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='current_telemetry_values',
            field=models.TextField(default=''),
        ),
    ]
