# Generated by Django 2.2.8 on 2020-02-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0002_atcontext_current_telemetry_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveATContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AT.ATContext')),
            ],
        ),
    ]
