# Generated by Django 2.2.8 on 2020-02-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0003_activeatcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='current_telemetry_info',
            field=models.TextField(default=''),
        ),
    ]
