# Generated by Django 2.2.8 on 2020-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0005_auto_20200212_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcontext',
            name='current_step',
            field=models.TextField(default=''),
        ),
    ]
