# Generated by Django 2.2.8 on 2020-02-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0006_auto_20200212_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcontext',
            name='current_step',
        ),
    ]
