# Generated by Django 2.2.8 on 2020-02-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0008_atcontext_current_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcontext',
            name='current_step',
        ),
    ]
