# Generated by Django 2.2.8 on 2020-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0009_remove_atcontext_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='current_step',
            field=models.TextField(default=''),
        ),
    ]
