# Generated by Django 2.2.8 on 2020-02-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0011_auto_20200212_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcontext',
            name='recent_anomalies',
        ),
        migrations.RemoveField(
            model_name='atcontext',
            name='recent_measurements',
        ),
        migrations.RemoveField(
            model_name='atcontext',
            name='recent_procedures',
        ),
    ]
