# Generated by Django 2.2.8 on 2020-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0013_remove_atcontext_current_procedure_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='are_at_threads_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
