# Generated by Django 3.0.9 on 2020-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0014_atcontext_are_at_threads_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='all_steps_from_procedure',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='atcontext',
            name='current_step_pointer',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='atcontext',
            name='next_step_pointer',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='atcontext',
            name='previous_step_pointer',
            field=models.IntegerField(default=-1),
        ),
    ]
