# Generated by Django 3.0.7 on 2020-09-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daphne_context', '0007_auto_20191111_1756'),
        ('AT', '0015_auto_20200909_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcontext',
            name='all_steps_from_procedure',
        ),
        migrations.RemoveField(
            model_name='atcontext',
            name='current_step_pointer',
        ),
        migrations.RemoveField(
            model_name='atcontext',
            name='next_step_pointer',
        ),
        migrations.RemoveField(
            model_name='atcontext',
            name='previous_step_pointer',
        ),
        migrations.CreateModel(
            name='ATDialogueContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_steps_from_procedure', models.TextField(default='')),
                ('next_step_pointer', models.IntegerField(default=-1)),
                ('previous_step_pointer', models.IntegerField(default=-1)),
                ('current_step_pointer', models.IntegerField(default=-1)),
                ('dialoguecontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.DialogueContext')),
            ],
        ),
    ]
