# Generated by Django 3.2.2 on 2021-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0016_auto_20200909_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='seen_tutorial',
            field=models.BooleanField(default=False),
        )
    ]
