# Generated by Django 3.0.7 on 2021-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AT', '0016_auto_20200909_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcontext',
            name='seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
