# Generated by Django 4.0.3 on 2022-03-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daphne_context', '0014_auto_20211231_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleDialogueContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialoguecontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.dialoguecontext')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=80)),
                ('dataset_user', models.BooleanField()),
                ('last_arch_id', models.IntegerField()),
                ('selected_arch_id', models.IntegerField()),
                ('added_archs_count', models.IntegerField()),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daphne_context.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eossdialoguecontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='example_problem.exampledialoguecontext')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('inputs', models.TextField()),
                ('outputs', models.TextField()),
                ('examplecontext', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_problem.examplecontext')),
            ],
            options={
                'unique_together': {('examplecontext', 'id')},
            },
        ),
    ]
